version: "3.9"

services:
  servlet:
    build: .
    ports:
      - "7777:8080"
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=mysql_user
      - MYSQL_DATABASE=todo